### ISSUE TITLE
tests are showing as status: interrupted and marked as failed.

### ISSUE THREAD

**Issue by amartanwar42** [BorisOsipov/wdio-reportportal-reporter#149]
## The problem

I am frequently getting this error. Where tests status is interrupted and marked as failed in reports.
But tests are actually passed.

In logs below error appears:
![image](https://user-images.githubusercontent.com/40663687/117000558-8857b300-ace1-11eb-866d-d123a1c9af4b.png)

Hence I am already using the below commands to solve the above error but actually, it's not helping I also tried giving a long time interval but that also dint work. I am still getting the above error.
	- reporterSyncInterval: 1000,
	- reporterSyncTimeout: 5 * 60 * 1000,

## Environment

* WebdriverIO version: 6.0.13
* wdio-reportportal-version version: 6.0.1
* Node.js version: 15.12.0
* WDIO Testrunner and version(mocha\cucumber\jasmine): 6.0.13

**Comment by BorisOsipov** [comment]
@amartanwar42 I have no clue what is wrong without reproducible example.

**Comment by ValeriiBorovyk** [comment]
Hi all, 
I've been faced the same issue:
Tests are marked as failed with status: interrupted, however, they are successfully passed on TeamCity
![image](https://user-images.githubusercontent.com/37636386/145187509-06542e64-2820-416c-a7c2-8a0f48ae3bd6.png)

Also, I see there was the same issue for reportportal/agent-python-pytest, and it was fixed in latest version - https://github.com/reportportal/agent-python-pytest/issues/266

I'm using: reportportal/agent-js-mocha  "5.0.1",  
    "wdio-reportportal-reporter": "^7.3.0",
    "wdio-reportportal-service": "^7.3.0",

Can you please fix this issue?

**Comment by BorisOsipov** [comment]
@ValeriiBorovyk Sure I can fix it if you provide [concise reproducible test case](http://sscce.org/) by sample project on github.
